{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pp-webhook.fullname" . }}-secrets
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  {{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | toString | b64enc }}
  {{- end }}
{{- end }}