image:
  pullPolicy: IfNotPresent

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations:
  logging: collect

podEnvFrom: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 80

deployment:
  labels: {}
  port: 8080
  healthPath: /health

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

appConfig:
  springProfiles: []
  environmentVariables: {}

prometheus:
  enabled: true
  path: /actuator/prometheus